### ISSUE TITLE
Epic m4a-firmware documentation review

### ISSUE THREAD

**Issue by luisan00** [Mesh4all/m4a-firmware#55]
- [x] README review
- [x] CODING_CONVENTION.md
- [x] CONTRIBUTING.md
- [x] CONTRIBUTORS
- [x] CODE_OF_CONDUCT.md
- [x] Repository Labels Review

**Comment by luisan00** [comment]
Done!
