### ISSUE TITLE
model board esp32-wroom

### ISSUE THREAD

**Issue by eduazocar** [Mesh4all/m4a-firmware#84]
To test a board without a wireless interface (if a board has one). the model of the board, the following diagram show the client board esp32-wroom, this is the main board esp32-wroom that will be develop 

![Graph](https://github.com/eduazocar/m4a-firmware/blob/boardm4a/test_develop/graph_board_esp32.jpg?raw=true)
### Tasks
- [ ] set ds18b20 pins
- [ ] set soil_moisture pins
- [ ] give support to UART2 in esp32-wroom boards

**Comment by luisan00** [comment]
> _No description provided.
where is the description? xD
